# script_file models_start_idx models_end_idx gpu_id

# scripts/week_energy_no_text.sh 0 1 0
# scripts/week_energy_add.sh 0 1 0
# scripts/week_energy_concat.sh 0 1 0
# scripts/week_energy_query.sh 0 1 0
# scripts/week_energy_text_ts_add.sh 0 1 0
# scripts/week_energy_text_ts_concat.sh 0 1 0
# scripts/week_energy_text_ts_query.sh 0 1 0
# scripts/week_climate_no_text.sh 0 1 0
# scripts/week_climate_add.sh 0 1 0
# scripts/week_climate_concat.sh 0 1 0
# scripts/week_climate_query.sh 0 1 0
# scripts/week_climate_text_ts_add.sh 0 1 0
# scripts/week_climate_text_ts_concat.sh 0 1 0
# scripts/week_climate_text_ts_query.sh 0 1 0
# scripts/week_climate_random_add.sh 0 1 0
# scripts/week_climate_random_concat.sh 0 1 0
# scripts/week_climate_random_query.sh 0 1 0
# scripts/month_economy.sh 0 1 0
# scripts/month_economy_random_add.sh 0 1 0
# scripts/month_economy_random_concat.sh 0 1 0
# scripts/month_economy_random_query.sh 0 1 0
# scripts/week_health.sh 0 1 0
# scripts/week_health_us_no_text.sh 0 1 0
# scripts/week_health_us_query.sh 0 1 0
# scripts/week_health_us_add.sh 0 1 0
# scripts/week_health_us_concat.sh 0 1 0
# scripts/day_environment_query.sh 0 1 0
# scripts/day_environment_no_text.sh 0 1 0
# scripts/day_environment_concat.sh 0 1 0
# scripts/month_agriculture_add.sh 0 1 0
# scripts/month_agriculture_concat.sh 0 1 0
# scripts/month_agriculture_query.sh 0 1 0
# scripts/month_agriculture_no_text.sh 0 1 0